(() => {
  const $ = (s, r=document) => r.querySelector(s);
  const $$ = (s, r=document) => [...r.querySelectorAll(s)];
  const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const val = id => ($(id)?.value || '').trim();
  const setOut = (text, meta='') => { const o=$('#radar-output'); if(o){ o.textContent=text; } const m=$('#radar-meta'); if(m)m.textContent=meta; };
  const copy = async () => { const o=$('#radar-output'); if(!o?.textContent) return; try{ await navigator.clipboard.writeText(o.textContent); const b=$('#copy-output'); if(b){const old=b.textContent;b.textContent='✓ Copiado';setTimeout(()=>b.textContent=old,1400);} }catch{ setOut(o.textContent+'\n\n[Selecciona y copia el resultado manualmente.]',$('#radar-meta')?.textContent||''); } };
  const lines = a => a.filter(Boolean).join('\n');
  const slug = s => s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
  const cleanList = s => s.split(/[,;\n]/).map(x=>x.trim()).filter(Boolean);
  const titleCase = s => s ? s.charAt(0).toUpperCase()+s.slice(1) : s;
  const pick = (a,i) => a[i % a.length];

  const configs = {
    'generador-de-prompts': {
      title:'Generador de prompts', intro:'Construye prompts completos y reutilizables para ChatGPT, Claude, Gemini, Perplexity y otras IA.',
      fields:[['objetivo','¿Qué quieres conseguir?','Escribe la tarea concreta que debe realizar la IA…','ta'],['contexto','Contexto y datos disponibles','Información que la IA debe conocer para responder bien…','ta'],['audiencia','Audiencia','Ej.: principiantes, clientes B2B, estudiantes…','text'],['formato','Formato de salida','Ej.: tabla, pasos, JSON, guion, lista…','text'],['tono','Tono','Profesional, cercano, persuasivo, técnico…','text'],['restricciones','Restricciones y criterios','Qué debe evitar, longitud, idioma, requisitos…','ta']],
      run(){const o=val('#objetivo');if(!o)return 'Escribe el objetivo para construir el prompt.';return lines(['ROL','Actúa como un especialista experto en la tarea solicitada.','', 'OBJETIVO',o,'','CONTEXTO',val('#contexto')||'Si falta información, identifica primero qué dato es imprescindible y no inventes hechos.','','AUDIENCIA',val('#audiencia')||'Adapta la respuesta al nivel de conocimiento del lector.','','INSTRUCCIONES','1. Analiza la petición antes de responder.\n2. Divide el trabajo en pasos lógicos cuando aporte claridad.\n3. Señala supuestos o incertidumbres relevantes.\n4. Prioriza precisión, utilidad y ejemplos concretos.','','FORMATO DE SALIDA',val('#formato')||'Entrega una respuesta clara, estructurada y fácil de reutilizar.','','TONO',val('#tono')||'Claro, natural y profesional.','','RESTRICCIONES',val('#restricciones')||'No inventes datos. Si una petición es ambigua, indica qué supuesto estás usando.','','CONTROL DE CALIDAD','Antes de finalizar, revisa que la respuesta cumpla el objetivo, el formato y las restricciones.']);}
    },
    'mejorador-de-prompts': {
      title:'Mejorador de prompts', intro:'Convierte una petición vaga en un prompt más claro, específico, controlable y fácil de reutilizar.',
      fields:[['objetivo','Prompt actual','Pega aquí tu prompt o una instrucción breve que quieras mejorar…','ta'],['contexto','Contexto adicional','Datos, producto, público, canal o situación que ayuden a precisar la tarea…','ta'],['audiencia','Audiencia','¿Para quién se genera la respuesta?','text'],['modelo','Tipo de IA / uso','Chat general, investigación, programación, imagen, vídeo, marketing…','text'],['formato','Formato deseado','Tabla, lista, guion, JSON, pasos, respuesta corta…','text']],
      run(){const p=val('#objetivo');if(!p)return 'Pega un prompt para mejorarlo.';const c=val('#contexto'),a=val('#audiencia'),m=val('#modelo'),f=val('#formato');const improved=lines(['ROL','Eres un experto en transformar instrucciones ambiguas en resultados precisos.','','TAREA',p,'','CONTEXTO',c||'Usa únicamente la información proporcionada y distingue hechos de supuestos.','','CRITERIOS DE MEJORA','• Define con precisión qué resultado se necesita.\n• Añade contexto útil sin introducir datos inventados.\n• Especifica audiencia y nivel de detalle.\n• Convierte preferencias implícitas en instrucciones verificables.\n• Define formato y criterios de calidad.\n• Evita pasos innecesarios y lenguaje ambiguo.','','AUDIENCIA',a||'La respuesta debe ser comprensible para el destinatario final.','','USO / MODELO',m||'Modelo de lenguaje general.','','FORMATO',f||'Usa encabezados y listas cuando mejoren la claridad.','','INSTRUCCIÓN FINAL','Si falta un dato imprescindible, formula una pregunta concreta antes de asumirlo. Revisa el resultado contra todos los requisitos antes de entregarlo.']);return improved+'\n\nDIAGNÓSTICO\n✓ Objetivo explicitado\n✓ Contexto separado de instrucciones\n✓ Formato y audiencia definidos\n✓ Criterios de calidad añadidos';}
    },
    'generador-de-titulos': {
      title:'Generador de títulos', intro:'Crea títulos con diferentes ángulos para YouTube, TikTok, blogs, newsletters, redes y páginas web.',
      fields:[['tema','Tema o contenido','Describe el contenido, producto o idea…','ta'],['plataforma','Plataforma','YouTube, TikTok, blog, LinkedIn, newsletter, web…','text'],['audiencia','Audiencia','A quién quieres atraer…','text'],['palabras','Palabras clave','Términos que deberían aparecer, separados por comas…','text'],['tono','Tono','Curioso, experto, urgente, emocional, elegante, directo…','text']],
      run(){const t=val('#tema');if(!t)return 'Escribe el tema para generar títulos.';const p=val('#plataforma')||'contenido digital',a=val('#audiencia')||'tu audiencia',k=cleanList(val('#palabras')),tone=val('#tono')||'directo';const key=k.length?' · '+k.slice(0,2).join(' · '):'';const arr=[`La guía definitiva de ${t}${key}`,`Lo que nadie te cuenta sobre ${t}` ,`${t}: 7 claves que debes conocer`,`Probé ${t} y esto fue lo que descubrí`,`Cómo conseguir mejores resultados con ${t}`,`El error que casi todos cometen con ${t}`,`${t}: qué funciona, qué no y por qué`,`Antes de empezar con ${t}, mira esto`,`De cero a experto: ${t} paso a paso`,`¿Vale la pena ${t}? La respuesta clara`,`5 ideas sobre ${t} que puedes aplicar hoy`,`La estrategia simple para mejorar ${t}`];return `Títulos para ${p} · tono ${tone}\nAudiencia: ${a}\n\n${arr.map((x,i)=>`${i+1}. ${x}`).join('\n')}`;}
    },
    'generador-de-ideas': {
      title:'Generador de ideas', intro:'Genera ángulos de contenido accionables, no simples frases repetidas.',
      fields:[['tema','Tema / nicho','Ej.: fitness, IA, inmobiliaria, cocina, educación…','ta'],['objetivo','Objetivo','Educar, vender, entretener, captar clientes, crecer…','text'],['plataforma','Plataforma','TikTok, YouTube, Instagram, blog, LinkedIn…','text'],['audiencia','Audiencia','Perfil de la persona a la que quieres llegar…','text'],['cantidad','Cantidad','Número de ideas (5–20)','number']],
      run(){const t=val('#tema');if(!t)return 'Escribe un tema o nicho.';const n=Math.min(20,Math.max(5,parseInt(val('#cantidad')||10,10)));const obj=val('#objetivo')||'aportar valor';const p=val('#plataforma')||'redes sociales';const a=val('#audiencia')||'personas interesadas en el tema';const angles=['error común','mito que conviene desmontar','tutorial paso a paso','comparativa','caso práctico','pregunta polémica','antes vs. después','lista de recursos','historia personal','reto de 7 días','preguntas frecuentes','tendencia explicada','checklist','experimento','opinión argumentada','secreto o atajo','reacción a una noticia','guía para principiantes','nivel avanzado','serie de contenidos'];return `Plan de ideas · ${p}\nObjetivo: ${obj}\nAudiencia: ${a}\nTema: ${t}\n\n${Array.from({length:n},(_,i)=>`${i+1}. ${titleCase(angles[i])}: ${t}. Crea una pieza que explique ${angles[i]} con un ejemplo concreto y termina con una acción útil para el público.`).join('\n')}`;}
    },
    'generador-de-hashtags': {
      title:'Generador de hashtags', intro:'Crea conjuntos de hashtags por intención, nicho y alcance, listos para copiar.',
      fields:[['tema','Tema','Tema principal de la publicación…','text'],['plataforma','Plataforma','TikTok, Instagram, YouTube, LinkedIn…','text'],['nicho','Nicho','Subtema o comunidad concreta…','text'],['audiencia','Audiencia','A quién quieres llegar…','text'],['cantidad','Cantidad','Número de hashtags (5–30)','number']],
      run(){const t=val('#tema');if(!t)return 'Escribe un tema.';const n=Math.min(30,Math.max(5,parseInt(val('#cantidad')||15,10)));const words=cleanList(t).concat(cleanList(val('#nicho')));const base=words.map(x=>slug(x)).filter(Boolean);const core=[...new Set(base.concat(['inteligenciaartificial','ia','tecnologia','aprende','consejos']))];const local=core.map(x=>'#'+x);const combos=core.flatMap(x=>['tips'+x,x+'facil',x+'paraprincipiantes']);const tags=[...new Set(local.concat(combos.map(x=>'#'+x)))].slice(0,n);return `Hashtags para ${val('#plataforma')||'redes sociales'}\nTema: ${t}\nNicho: ${val('#nicho')||'general'}\n\n${tags.join(' ')}\n\nEstrategia: mezcla etiquetas muy específicas del nicho con algunas de contexto amplio. Evita usar hashtags irrelevantes solo por volumen.`;}
    },
    'contador-de-palabras': {
      title:'Contador y analizador de texto', intro:'Analiza palabras, caracteres, frases, párrafos, tiempo de lectura y densidad de palabras.',
      fields:[['texto','Texto','Pega aquí el texto que quieres analizar…','ta']],
      run(){const t=val('#texto');if(!t)return 'Pega un texto para analizarlo.';const words=t.match(/\b[\p{L}\p{N}’'-]+\b/gu)||[];const sentences=(t.match(/[.!?]+(?=\s|$)/g)||[]).length;const paragraphs=t.split(/\n\s*\n/).filter(x=>x.trim()).length;const chars=t.length, no=t.replace(/\s/g,'').length;const mins=words.length/200, speak=words.length/130;const freq={};words.map(w=>w.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')).forEach(w=>{if(w.length>3)freq[w]=(freq[w]||0)+1});const top=Object.entries(freq).sort((a,b)=>b[1]-a[1]).slice(0,8).map(([w,c])=>`${w}: ${c}`).join(', ');return `PALABRAS: ${words.length}\nCARACTERES: ${chars}\nCARACTERES SIN ESPACIOS: ${no}\nFRASES APROX.: ${sentences}\nPÁRRAFOS: ${paragraphs}\nTIEMPO DE LECTURA: ${Math.max(1,Math.ceil(mins))} min\nTIEMPO DE LOCUCIÓN: ${Math.max(1,Math.ceil(speak))} min\n\nPALABRAS MÁS REPETIDAS\n${top||'—'}\n\nCONSEJO\nUsa estos datos como orientación editorial; la legibilidad también depende de la complejidad y del público.`;}
    },
    'descripcion-video': {
      title:'Generador de descripciones para vídeo', intro:'Prepara descripciones optimizadas para YouTube, TikTok y otras plataformas, con CTA y estructura reutilizable.',
      fields:[['tema','Tema / título del vídeo','Qué ocurre o qué enseña el vídeo…','ta'],['plataforma','Plataforma','YouTube, TikTok, Instagram, LinkedIn…','text'],['audiencia','Audiencia','A quién va dirigido…','text'],['keywords','Palabras clave','Separadas por comas…','text'],['cta','Llamada a la acción','Suscríbete, comenta, visita, descarga…','text'],['tono','Tono','Educativo, cercano, experto, entretenido…','text']],
      run(){const t=val('#tema');if(!t)return 'Describe el vídeo o escribe su título.';const p=val('#plataforma')||'YouTube',a=val('#audiencia')||'personas interesadas en el tema',k=cleanList(val('#keywords')),cta=val('#cta')||'Suscríbete y comparte tu opinión',tone=val('#tono')||'cercano';return `${t}\n\nEn este vídeo descubrirás los puntos clave de ${t.toLowerCase()}, explicado de forma ${tone} y práctica para ${a}. Encontrarás ideas, ejemplos y pasos que puedes aplicar desde hoy.\n\n👉 ${cta}.\n\nPALABRAS CLAVE\n${k.length?k.join(' · '):'Añade palabras clave específicas del contenido'}\n\n#IA #Tecnologia #Aprendizaje\n\nEstructura adaptada a ${p}. Revisa la descripción antes de publicar para añadir enlaces, capítulos o información específica del vídeo.`;}
    },
    'prompt-imagenes': {
      title:'Generador de prompts para imágenes', intro:'Construye prompts visuales detallados con sujeto, composición, cámara, luz, estilo, ambiente y negativos.',
      fields:[['sujeto','Sujeto / escena','Qué debe aparecer y qué está haciendo…','ta'],['estilo','Estilo visual','Fotografía, 3D, ilustración, cinematográfico, anime…','text'],['composicion','Composición / encuadre','Primer plano, plano general, simetría, regla de tercios…','text'],['camara','Cámara / óptica','Ej.: 35mm, 85mm, profundidad de campo…','text'],['luz','Iluminación','Hora dorada, estudio, neón, contraluz…','text'],['ambiente','Ambiente / color','Emoción, paleta, clima, época, escenario…','text'],['formato','Formato','9:16, 16:9, 1:1…','text'],['negativos','Evitar','Texto, manos deformes, baja resolución, objetos extra…','text']],
      run(){const s=val('#sujeto');if(!s)return 'Describe el sujeto o escena.';return `PROMPT\n${s}. ${val('#estilo')||'Estética visual cuidada y coherente'}, ${val('#composicion')||'composición equilibrada'}, ${val('#camara')||'perspectiva natural con profundidad de campo'}, ${val('#luz')||'iluminación cinematográfica suave'}, ${val('#ambiente')||'atmósfera detallada y expresiva'}, alta calidad, detalles limpios, materiales y texturas definidos, profundidad y separación visual del sujeto, resultado coherente de principio a fin.\n\nFORMATO: ${val('#formato')||'9:16'}\n\nNEGATIVE PROMPT\n${val('#negativos')||'texto ilegible, marcas de agua, elementos duplicados, anatomía deformada, baja resolución, ruido excesivo, composición confusa'}`;}
    }
  };

  const key = document.body.dataset.tool;
  const cfg = configs[key];
  if(!cfg) return;
  const form=$('#radar-form');
  cfg.fields.forEach(([id,label,ph,type])=>{
    const wrap=document.createElement('div'); wrap.className=type==='ta'?'field field-wide':'field';
    const lab=document.createElement('label');lab.setAttribute('for',id);lab.textContent=label;wrap.appendChild(lab);
    const el=type==='ta'?document.createElement('textarea'):document.createElement('input');el.id=id;el.name=id;el.placeholder=ph;if(type==='number'){el.type='number';el.min='5';el.max='30';el.value='10';}wrap.appendChild(el);form.appendChild(wrap);
  });
  $('#tool-title').textContent=cfg.title; $('#tool-intro').textContent=cfg.intro;
  $('#run-tool').addEventListener('click',()=>{setOut(cfg.run(),'Resultado generado en tu navegador · sin cuenta y sin API externa.');});
  $('#copy-output').addEventListener('click',copy);
  $('#clear-tool').addEventListener('click',()=>{form.reset();setOut('Aquí aparecerá tu resultado.','Listo para empezar.');});
  $('#sample-tool')?.addEventListener('click',()=>{const first=cfg.fields[0][0];const e=$('#'+first);if(e)e.value=first==='objetivo'?'Crear una estrategia de contenidos para una marca de tecnología':first==='tema'?'inteligencia artificial para principiantes':first==='texto'?'La inteligencia artificial está cambiando la forma de crear, investigar y trabajar. Este texto sirve como ejemplo para probar el analizador.':'Crear contenido útil y práctico sobre inteligencia artificial'; $('#run-tool').click();});
})();